server:
  port: 9090
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/war_jee_w_24?serverTimezone=UTC
    username: root
    password: root