server:
  port: 9090
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/war_jee_w_24?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
#   https://www.baeldung.com/hibernate-field-naming-spring-boot
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
